---
- name: install initial packages on all servers
  hosts: web
  remote_user: ansible
  become: yes

  tasks:
  - name: install all initial packages
    yum:
      name: ['man', 'man-pages', 'mlocate', 'vim', 'bind-utils']
      state: latest

  tasks: 
  - name: Manage resolv.conf
    template: 
      src: templates/resolv.conf
      dest: /etc/resolv.conf
 
  tasks:
  - name: install chrony
    yum:
      name: chrony
      state: latest

  - name: configure chrony
    template:
      src: templates/chrony.conf.j2
      dest: /etc/chrony.conf

  - name: start chrony service
    service:
      name: chronyd
      state: started
  handlers:
    - name: restart chronyd
      service: 
        name: chronyd
        state: restarted
